export { ApolloUser } from './apollo-user';
export { ButtonDescription } from './button-description';
export { University } from './university';
export { UniversityCompletionYear } from './university-completion-year';
export { UniversityFaculty } from './university-faculty.d';
export { UniversityMajorSubjectGroup, UniversityMajorSubjectGroupSubject } from './university-major-subject-group.d';
export { UniversityMajor } from './university-major.d';
export { UniversityScholarshipData, UniversityScholarshipYear } from './university-scholarship-year.d';
export { UniversitySpecialization, UniversitySpecializationSubjectGroup } from './university-specialization.d';
export { UniversitySubjectCompletion } from './university-subject-completion';
export { RawUniversitySubject, UniversitySubject } from './university-subject.d';
